Experiment No.9

Aim : Study of Numpy Library

Madhur Gupta

25070123070


In [13]:
#why Numpy?
#faster than lists
# used for numerical compututational
# base for pandas



In [ ]:
# data should be in matrix fpr numpy


In [14]:
#Declaration of Numpy
import numpy as np

a = np.array([1,10,20,30,40,50,500])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[  1  10  20  30  40  50 500]
[[1 2 3]
 [4 5 6]]


In [15]:
#Dimension of Array(it is used to know whether it is 1 d ,2 d )
print(a.ndim)
print(b.ndim)

1
2


In [16]:
#size of matrix
print(a.size)
print(b.size)

7
6


In [17]:
print(a.shape)
print(b.shape)

(7,)
(2, 3)


In [23]:
a.dtype

dtype('int64')

In [28]:
# In built function using Numpy
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.ones((2,3) ,dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [49]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [51]:
print(b * 2)
print(b + 2)

[[ 2  4  6]
 [ 8 10 12]]
[[3 4 5]
 [6 7 8]]


In [52]:
print(np.mean(a))

93.0


In [54]:
print(np.sum(a))

651
